src/Models/Widget.cs
using System;
using System.Linq;
using System.Linq.Expressions;
using PagingExample.Data;

namespace PagingExample.Models{

    public class Widget{

        public Guid Id{get;set;}
        public string Name {get;set;}
        public string PartNumber{get;set;}
        public string Description {get;set;}
        public int Quantity{get;set;}
        public double Price {get;set;}
    }

public static class WidgetQueryExtensions{

    public static IQueryable<Widget> Filter(this IQueryable<Widget> query, string filter){
        if(string.IsNullOrWhiteSpace(filter)){
            return query;
        }

        filter = filter.ToLower();

        return query.Where(x =>
            x.Name.ToLower().Contains(filter)
            || x.PartNumber.ToLower().Contains(filter)
            || x.Description.ToLower().Contains(filter)
        );
    }

    public static IQueryable<Widget> OrderBy(this IQueryable<Widget> query, string name, SortDirection direction = SortDirection.Asc){

        Expression<Func<Widget, object>> exp = name?.ToLower() switch
        {
            "part" => x => x.PartNumber,
            "description" => x => x.Description,
            "quantity" => x => x.Quantity,
            "price" => x => x.Price,
            "quantityprice" => x => x.Quantity + x.Price,
            _ => x => x.Name
        };

        return direction == SortDirection.Asc ? query.OrderBy(exp) : query.OrderByDescending(exp);
    }
  }

}

src/Pages/Components/Pagination/PaginationViewComponent.cs
using System.Collections.Generic;
using PagingExample.Models;
using Microsoft.AspNetCore.Mvc;

namespace PagingExample.Pages.Components.Pagination
{
    public class PaginationViewComponent: ViewComponent
    {
        public PaginationViewComponent() { }
        public IViewComponentResult Invoke(IPaginatedList values, Dictionary<string,string> routeData = null)
        {
            return View("Default", new PaginationViewModel(){List = values, RouteData = routeData});
        }
    }

    public class PaginationViewModel
    {
        public IPaginatedList List { get; set; }
        public Dictionary<string, string> RouteData { get; set; }
    }
}

src/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace PagingExample.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

src/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace PagingExample.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

src/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace PagingExample.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

src/Pages/Widgets.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PagingExample.Data;
using PagingExample.Models;
using Faker;
using PagingExample.Configuration;

namespace PagingExample.Pages
{
    public class WidgetsModel : PageModel
    {
        private readonly ApplicationDbContext _dbContext;

        public WidgetsModel(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
            Sort = "name";
        }

        public PaginatedList<Widget> Widgets{get;set;}

        [BindProperty(SupportsGet = true, Name = "p")]
        public int PageIndex { get; set; } = 1;

        [BindProperty(SupportsGet = true)]
        public string Filter { get; set; }

        [BindProperty(SupportsGet = true)]
        public string Sort { get; set; }

        [BindProperty(SupportsGet = true)]
        public SortDirection Direction { get; set; }

         public Dictionary<string, string> LinkData =>
            new()
            {
                {"filter", Filter},
                {"p", Widgets.CurrentPage.ToString()},
                {"sort", Sort},
                {"direction", Direction.ToString()}
            };

        public async Task<IActionResult> OnGetAsync()
        {
            Widgets = await _dbContext.Widgets
                                .Filter(Filter)
                                .OrderBy(Sort, Direction)
                                .ToPagedList(PageIndex, AppConfig.PageSize);

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(){

            for(int i = 0; i < 100; i++){
                var widget = new Widget(){
                    Id = Guid.NewGuid(),
                    Name = string.Join(" ",Faker.Lorem.Words( (i % 2) + 1)),
                    Description = Faker.Lorem.Sentence(),
                    PartNumber = Faker.Identification.UsPassportNumber(),
                    Quantity = Faker.RandomNumber.Next(0, 10000),
                    Price = decimal.ToDouble(Faker.Finance.Coupon())
                };

                await _dbContext.Widgets.AddAsync(widget);
            }

            await _dbContext.SaveChangesAsync();

            return RedirectToPage("./Widgets");
        }

        public SortDirection GetNextSortDirection(string name, SortDirection defaultOrder){
            if(Sort?.ToLower() != name?.ToLower()){
                return defaultOrder;
            }


            return Direction == SortDirection.Asc? SortDirection.Desc: SortDirection.Asc;
        }
    }
}

src/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/Pages/Widgets.cshtml
@page
@model PagingExample.Pages.WidgetsModel
@{
   Layout="_Layout";
}

<h2>Widgets</h2>
<hr/>

<div class="container-fluid">
   <div class="row pb-2">
      <div class="col-6">
         <form method="get" name="filterForm" >
            <input class="form-control" asp-for="Filter" placeholder="filter" autofocus/>
         </form>
      </div>
      <div class="col-6 text-right">
      </div>
   </div>

   <table class="table table-hover table-striped">
      <thead>
         <tr>
             <th>
               <a asp-route-filter="@Model.Filter" asp-route-sort="name" asp-route-direction="@Model.GetNextSortDirection("name", SortDirection.Asc)">
                  Name
               </a>
             </th>
             <th>
                <a asp-route-filter="@Model.Filter" asp-route-sort="part" asp-route-direction="@Model.GetNextSortDirection("part", SortDirection.Desc)">
                Part Number
                </a>
            </th>
             <th>
                <a asp-route-filter="@Model.Filter" asp-route-sort="description" asp-route-direction="@Model.GetNextSortDirection("description", SortDirection.Desc)">
                Description
                </a>
            </th>
             <th>
                <a asp-route-filter="@Model.Filter" asp-route-sort="quantity" asp-route-direction="@Model.GetNextSortDirection("quantity", SortDirection.Desc)">
                Quantity
                </a>
            </th>
             <th>
                <a asp-route-filter="@Model.Filter" asp-route-sort="price" asp-route-direction="@Model.GetNextSortDirection("price", SortDirection.Desc)">
                  Price
                </a>
             </th>
             <th>
                <a asp-route-filter="@Model.Filter" asp-route-sort="quantityprice" asp-route-direction="@Model.GetNextSortDirection("quantityprice", SortDirection.Desc)">
                  Quanity - Price
                </a>
             </th>
         </tr>
      </thead>
      <tbody>
         @foreach(var w in Model.Widgets){
             <tr>
                 <td>@w.Name</td>
                 <td>@w.PartNumber</td>
                 <td>@w.Description</td>
                 <td>@w.Quantity</td>
                 <td>@w.Price.ToString("C")</td>
                 <td>
                    @w.Quantity / @w.Price.ToString("C")
                 </td>
             </tr>
         }

         @if(Model.Widgets.TotalItems == 0){
            <tr>
               <td colspan="10" class="text-center">
                   no widgets available
                   @if(string.IsNullOrWhiteSpace(Model.Filter)){
                    <form method="post">
                        <button type="submit" class="btn btn-primary">Create Demo Data</button>
                    </form>
                   }
               </td>
            </tr>
         }
      </tbody>
   </table>

   <vc:pagination values="Model.Widgets" route-data="Model.LinkData"/>

</div>